AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Psipay backend (API + cache)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        CACHE_TABLE_NAME: !Ref CacheTable
        DEFAULT_HISTORY_MONTHS: '12'
        ONS_CPIH_VERSION: '66'

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
      Events:
        Products:
          Type: Api
          Properties:
            Path: /products/{category}
            Method: GET
        Compare:
          Type: Api
          Properties:
            Path: /compare
            Method: POST
        Recommendations:
          Type: Api
          Properties:
            Path: /recommendations
            Method: POST
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/app.ts
        Format: cjs
        Minify: true
        Target: es2020
        Sourcemap: true

  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cacheKey
          AttributeType: S
      KeySchema:
        - AttributeName: cacheKey
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttlEpoch
        Enabled: true

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
