AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Psipay backend (API + cache)

Parameters:
  WebsiteBucketName:
    Type: String
    Description: "Unique S3 bucket name for SPA hosting"
    Default: "psipay-local-website"
  GeminiApiKey:
    Type: String
    Default: ""
    NoEcho: true
    Description: "Optional Gemini API key (used by /recommendations when enabled)"
  DynamoDbEndpoint:
    Type: String
    Default: ""
    Description: "Local DynamoDB endpoint for SAM local (leave empty in deployed env)"
  LogsRetentionDays:
    Type: Number
    Default: 14
    Description: "CloudWatch Logs retention for Lambda log group"
  ApiThrottleRateLimit:
    Type: Number
    Default: 5
    Description: "API Gateway steady-state requests per second limit"
  ApiThrottleBurstLimit:
    Type: Number
    Default: 10
    Description: "API Gateway burst requests limit"
  AllowClientGeminiKey:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: "Allow client-provided Gemini API key via X-Gemini-Api-Key header"

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 40
    MemorySize: 512
    Environment:
      Variables:
        CACHE_TABLE_NAME: !Ref CacheTable
        DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
        DEFAULT_HISTORY_MONTHS: '12'
        ONS_CPIH_VERSION: '66'
        GEMINI_API_KEY: !Ref GeminiApiKey
        ALLOW_CLIENT_GEMINI_KEY: !Ref AllowClientGeminiKey

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization,X-Gemini-Api-Key'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingRateLimit: !Ref ApiThrottleRateLimit
          ThrottlingBurstLimit: !Ref ApiThrottleBurstLimit
      Tags:
        psipay: "true"

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.handler
      Tags:
        psipay: "true"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CacheTable
      Events:
        Products:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /products/{category}
            Method: GET
        Compare:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /compare
            Method: POST
        RecommendationsGet:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /recommendations
            Method: GET
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /health
            Method: GET
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - src/app.ts
        Format: cjs
        Minify: true
        Target: es2020
        Sourcemap: true

  CacheTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Cache
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: cacheKey
          AttributeType: S
      KeySchema:
        - AttributeName: cacheKey
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttlEpoch
        Enabled: true
      Tags:
        - Key: psipay
          Value: "true"

  ApiFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ApiFunction}"
      RetentionInDays: !Ref LogsRetentionDays
      Tags:
        - Key: psipay
          Value: "true"

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-users"
      AutoVerifiedAttributes: []
      UsernameAttributes: []
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireUppercase: false
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: false
          Mutable: true
      UserPoolTags:
        psipay: "true"

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-web-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
      SupportedIdentityProviders:
        - COGNITO

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteBucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      Tags:
        - Key: psipay
          Value: "true"

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  ApiBaseUrl:
    Description: API base URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  WebsiteUrl:
    Description: S3 static website URL
    Value: !Sub "http://${WebsiteBucket}.s3-website.${AWS::Region}.amazonaws.com"

  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Description: Cognito User Pool App Client ID
    Value: !Ref CognitoUserPoolClient

  CognitoRegion:
    Description: Cognito region for auth calls
    Value: !Ref AWS::Region
